### PR TITLE
Add rudimentary support for getting history

### PR DESCRIPTION
**Pull request by twitchy-ears**
Very similar to bookmarks and subscriptions, add ability to pull history items getting the same work data as per a bookmark but also numbers of times visited and last date visited.

### CODE REVIEW

**Comment by ArmindoFlores** [comment]
Because this is a kind of a major change I'll have to test it a bit more, but it seems pretty good to me

**Comment by twitchy-ears** [comment]
I'd hold off 24 hours and I'll send in another PR tomorrow?

I'm finding a couple of bugs, specifically issues around the code I nicked from the bookmarks section and I've got a new version with option sleeps and maximum history page loads because the person I asked to test this hit the rate limit before they could get through their history

**Comment by ArmindoFlores** [comment]
So should I still test it? Or are you thinking of making another PR?

**Comment by twitchy-ears** [comment]
Just submitted a revised version, sorry there was other things getting in the way of time :)

**Pull request closed without merging**
